export  const allMovies = [
  {
    id: 1,
    title: "The Dark Knight",
    image: "./assets/films/darknight.webp",
    year: "2008",
    duration: "2h32",
    rating: "4.8/5",
    genres: ["Action", "Crime", "Drama"],
  },
  {
    id: 2,
    title: "Interstellar",
    image: "./assets/films/Interstellar_film_poster.jpg",
    year: "2014",
    duration: "2h49",
    rating: "4.7/5",
    genres: ["Sci-Fi", "Drama"],
  },
  {
    id: 3,
    title: "Pulp Fiction",
    image: "./assets/films/pulp_fiction.jpg",
    year: "1994",
    duration: "2h34",
    rating: "4.6/5",
    genres: ["Action", "Crime", "Drama"],
  },
  {
    id: 4,
    title: "Inception",
    image: "./assets/films/inception.webp",
    year: "2010",
    duration: "2h28",
    rating: "4.5/5",
    genres: ["Sci-Fi", "Dark"],
  },
  {
    id: 5,
    title: "Forrest Gump",
    image: "./assets/films/forrest_gump.jpg",
    year: "1994",
    duration: "2h34",
    rating: "4.6/5",
    genres: ["Action", "Crime", "Drama"],
  },
  {
    id: 6,
    title: "The Matrix",
    image: "./assets/films/matrix.jpeg",
    year: "1999",
    duration: "2h16",
    rating: "4.5/5",
    genres: ["Sci-Fi", "Action"],
  },
];